// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication5.Entity;

#nullable disable

namespace WebApplication5.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230328084011_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication5.Entity.DIADIEM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENDIADIEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DIADIEMs", (string)null);
                });

            modelBuilder.Entity("WebApplication5.Entity.image_DIADIEM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_DIADIEM")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("id_DIADIEM");

                    b.ToTable("image_DIADIEM", (string)null);
                });

            modelBuilder.Entity("WebApplication5.Entity.image_DIADIEM", b =>
                {
                    b.HasOne("WebApplication5.Entity.DIADIEM", "dIADIEM")
                        .WithMany("image_DIADIEMs")
                        .HasForeignKey("id_DIADIEM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dIADIEM");
                });

            modelBuilder.Entity("WebApplication5.Entity.DIADIEM", b =>
                {
                    b.Navigation("image_DIADIEMs");
                });
#pragma warning restore 612, 618
        }
    }
}
